apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - name: grpc
      port: 8380
      # nodePort: # Optional field by default and for convenience, the Kubernetes control plane will allocate a port from a range
      protocol: TCP
      targetPort: 8380
  type: NodePort